### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by berkandirim** [dashersw/erste-demo#1]
```
/Users/berkandirim/Sites/erste.js-demo/tasks/templates.js:37
    var passEvents = [...arguments];
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/berkandirim/Sites/erste.js-demo/Gulpfile.js:16:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
```

**Comment by dashersw** [comment]
Hello @berkandirim ! It looks like you are running an older version of Node.js which doesn't support the new spread syntax. Here's more info: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)

I would advise, if possible, to use a newer Node.js version.
